baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Li Li's Website"
subtitle = "Testing"
theme = "ananke"
Paginate = 20 # this is set low for demonstrating with dummy content. Set to a higher number

[params]
  text_color = ""
  author = "Li Li"
  favicon = ""
  site_logo = ""
  description = "A Website about my Research and Teaching."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  recent_posts_number = 3
  body_classes = "roboto bg-near-white"

[[menu.main]]
  name = "Personal Info and Research"
  url = "/CV"
  weight = 95


[[menu.main]]
  name = "Teaching"
  url = "/Teaching"
  weight = 120

[[menu.main]]
  name = "All Posts"
  url = "/posts"
  weight = 150